export const Data = {
    "bonds": [
        {
            "category": "Tax Free Bonds",
            "coupon": "7.0%",
            "security": "HUDCO Tax Free 2023",
            "maturity": "28-Mar-23",
            "ip": "28th Mar",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "2.00 Lacs",
            "yield/price": "4.00%",
            "isin": "INE031A07873"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "7.4%",
            "security": "PFC Tax Free 2028",
            "maturity": "04-Jan-28",
            "ip": "04th Jan",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "8.00 Lacs",
            "yield/price": "5.30%",
            "isin": "INE134E07349"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "7.2%",
            "security": "PFC Tax Free 2023",
            "maturity": "04-Jan-23",
            "ip": "MMY",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "8.25 Lacs",
            "yield/price": "4.00%",
            "isin": "INE134E07331"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "8.50%",
            "security": "IIFCL Tax Free 2033",
            "maturity": "12-Nov-33",
            "ip": "12th Nov",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "25.00 Lacs",
            "yield/price": "5.4%",
            "isin": "INE787H07305"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "8.7%",
            "security": "NHPC Tax Free 2033",
            "maturity": "02-Nov-33",
            "ip": "01st Apr",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs  (Up to 40 Lacs)",
            "yield/price": "5.4%",
            "isin": "INE848E07534"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "8.5%",
            "security": "IIFCL Tax Free 2028",
            "maturity": "05-Sep-28",
            "ip": "05th Sep",
            "rating": "AAA",
            "fv": "10 Lacs",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "5.4%",
            "isin": "INE787H07255"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "7.40%",
            "security": "IIFCL Tax Free 2033",
            "maturity": "22-Jan-33",
            "ip": "22nd Jan",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "5.4%",
            "isin": "INE787H07156"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "8.7%",
            "security": "IIFCL Tax Free 2034",
            "maturity": "22-Jan-34",
            "ip": "22nd Jan",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "Multiples of 1 cr",
            "yield/price": "5.4%",
            "isin": "INE787H07347"
        },
        {
            "category": "Tax Free Bonds",
            "coupon": "8.7%",
            "security": "IIFCL Tax Free 2034",
            "maturity": "22-Jan-34",
            "ip": "22nd Jan",
            "rating": "AAA",
            "fv": "1000",
            "quantum": "5.00 cr",
            "yield/price": "5.4%",
            "isin": "INE787H07347"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "9.70%",
            "security": "U.P. Power Corporation Ltd 2025 (Secured)",
            "maturity": "01-Jul-2024: 25% 30-Sep-2024: 25%31-Dec-2024: 25% 31-Mar-2025: 25%",
            "ip": "30th Jun/30th Sep/31st Dec/31st  Mar",
            "rating": "A+(CE) by CRISIL & IND rating",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "9.2%",
            "isin": "INE540P07368"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "9.70%",
            "security": "U.P. Power Corporation Ltd 2028 (Secured)",
            "maturity": "30-Jun-2027: 25% 30-Sep-2027: 25%31-Dec-2027: 25% 31-Mar-2028: 25%",
            "ip": "30th Jun/30th Sep/31st Dec/31st  Mar",
            "rating": "A+(CE) by CRISIL & IND rating",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "9.5%",
            "isin": "INE540P07392"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "9.70%",
            "security": "U.P. Power Corporation Ltd 2029 (Secured)",
            "maturity": "30-Jun-2028: 25% 29-Sep-2028: 25%29-Dec-2028: 25% 30-Mar-2029: 25%",
            "ip": "30th Jun/30th Sep/31st Dec/31st  Mar",
            "rating": "A+(CE) by CRISIL & IND rating",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "9.50%",
            "isin": "INE540P07400"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "9.70%",
            "security": "U.P. Power Corporation Ltd 2030 (Secured)",
            "maturity": "29-Jun-2029: 25% 28-Sep-2029: 25%31-Dec-2029: 25% 29-Mar-2030: 25%",
            "ip": "30th Jun/30th Sep/31st Dec/31st  Mar",
            "rating": "A+(CE) by CRISIL & IND rating",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs\n(Upto 30 Lacs)",
            "yield/price": "9.6%",
            "isin": "INE540P07418"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "9.70%",
            "security": "U.P. Power Corporation Ltd 2031 (Secured)",
            "maturity": "28-Jun-2030: 25% 30-Sep-2030: 25%31-Dec-2030: 25% 31-Mar-2031: 25%",
            "ip": "30th Jun/30th Sep/31st Dec/31st  Mar",
            "rating": "A+(CE) by CRISIL & IND rating",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs\n(Limited quantum)",
            "yield/price": "9.6%",
            "isin": "INE540P07426"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "9.70%",
            "security": "U.P. Power Corporation Ltd 2032 (Secured)",
            "maturity": "30-Jun-2031: 25% 30-Sep-2031: 25%31-Dec-2031: 25% 22-Mar-2032: 25%",
            "ip": "30th Jun/30th Sep/31st Dec/31st  Mar",
            "rating": "A+(CE) by CRISIL & IND rating",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs\n(Limited quantum)",
            "yield/price": "9.6%",
            "isin": "INE540P07434"
        },
        {
            "category": "STATE GUARANTEE BONDS",
            "coupon": "10.2%",
            "security": "U.P.Power Corporation Ltd 2025 (Secured)",
            "maturity": "19-Apr-2024: 25% 19-Jul-2024: 25%18-Oct-2024: 25% 20-Jan-2025: 25%",
            "ip": "20th Jan/20th Apr/20th Jul/20th Oct",
            "rating": "A+(CE) by CRISIL, IND rating & AA-(CE) by BWR",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs\n(Up To 30 Lacs)",
            "yield/price": "8.6%",
            "isin": "INE540P07327"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.3%",
            "security": "Bank of Baroda Perp",
            "maturity": "17-Jul-25",
            "ip": "17th Jul",
            "rating": "AA+ by CRISIL & IND ratings",
            "fv": "10 Lacs",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.6%",
            "isin": "INE028A08216"
        },
        {
            "category": "PSU BONDS",
            "coupon": "7.7%",
            "security": "State Bank of India Perp",
            "maturity": "16-Sep-25",
            "ip": "09th Sep",
            "rating": "AA+ by CRISIL & IND ratings",
            "fv": "10 Lacs",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.4%",
            "isin": "INE062A08249"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.7%",
            "security": "Union Bank Perp",
            "maturity": "23-Jul-27",
            "ip": "25th Jul",
            "rating": "AA by CRISIL & IND ratings",
            "fv": "1 cr",
            "quantum": "Multiple of 1 Cr",
            "yield/price": "100.5",
            "isin": "INE692A08193"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.50%",
            "security": "Union Bank Perp",
            "maturity": "02-Mar-27",
            "ip": "02nd Mar",
            "rating": "AA by CRISIL & IND ratings",
            "fv": "1 cr",
            "quantum": "Multiple of 1 Cr",
            "yield/price": "8.6%",
            "isin": "INE692A08185"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.70%",
            "security": "Union Bank Perp",
            "maturity": "20-Nov-26",
            "ip": "22nd Nov",
            "rating": "AA by CRISIL & IND ratings",
            "fv": "1 cr",
            "quantum": "Multiple of 1 Cr",
            "yield/price": "8.5%",
            "isin": "INE692A08169"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.8%",
            "security": "Punjab National Bank Perp",
            "maturity": "06-Jul-27",
            "ip": "06th Jul",
            "rating": "AA by CRISIL & AA+ by IND ratings",
            "fv": "1 cr",
            "quantum": "Multiples of 1 Cr",
            "yield/price": "100.75",
            "isin": "INE160A08225"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.2%",
            "security": "Canara Bank Perp",
            "maturity": "19-Jul-27",
            "ip": "19th Jul",
            "rating": "AA+ by CRISIL & IND ratings",
            "fv": "1 cr",
            "quantum": "Multiples of 1 Cr",
            "yield/price": "100.38",
            "isin": "INE476A08167"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.4%",
            "security": "Indian Bank Perp",
            "maturity": "19-Dec-25",
            "ip": "30th Dec",
            "rating": "AA+ by CRISIL & CARE",
            "fv": "10 Lacs",
            "quantum": "1.00 cr",
            "yield/price": "8.30%",
            "isin": "INE562A08073"
        },
        {
            "category": "PSU BONDS",
            "coupon": "7.50%",
            "security": "PFC Ltd. 2031 (Secured) (Floating to 10 yr G-sec 5.85 G-Sec 2030)",
            "maturity": "22-Jan-31",
            "ip": "22nd Jan",
            "rating": "AAA by CARE, CRISIL & ICRA",
            "fv": "1000",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.60%",
            "isin": "INE134E07AP6"
        },
        {
            "category": "PSU BONDS",
            "coupon": "7.50%",
            "security": "PFC Ltd. 2031 (Secured) (Floating to 10 yr G-sec 5.85 G-Sec 2030)",
            "maturity": "22-Jan-31",
            "ip": "22nd Jan",
            "rating": "AAA by CARE, CRISIL & ICRA",
            "fv": "1000",
            "quantum": "Multiples of 1 Cr",
            "yield/price": "7.6%",
            "isin": "INE134E07AP6"
        },
        {
            "category": "PSU BONDS",
            "coupon": "9.6%",
            "security": "State Bank of India Perp",
            "maturity": "04-Dec-23",
            "ip": "04th Dec",
            "rating": "AA+ by CRISIL & ICRA",
            "fv": "10 Lacs",
            "quantum": "Multiples of 5 cr",
            "yield/price": "7.0%",
            "isin": "INE062A08173"
        },
        {
            "category": "PSU BONDS",
            "coupon": "8.2%",
            "security": "Canara Bank Perp",
            "maturity": "19-Jul-27",
            "ip": "19th Jul",
            "rating": "AA+ by CRISIL & IND ratings",
            "fv": "1 cr",
            "quantum": "Multiples of 5 cr",
            "yield/price": "100.32",
            "isin": "INE476A08167"
        },
        {
            "category": "PSU BONDS",
            "coupon": "7.4%",
            "security": "NTPC Ltd 2032 (Unsecured)",
            "maturity": "25-Aug-32",
            "ip": "25th Aug",
            "rating": "AAA by CARE, CRISIL & ICRA",
            "fv": "10 Lacs",
            "quantum": "5.00 cr",
            "yield/price": "100.25",
            "isin": "INE733E08221"
        },
        {
            "category": "Private BONDS",
            "coupon": "9.2%",
            "security": "Yes Bank Ltd 2025 (Tier - II)",
            "maturity": "30-Jun-25",
            "ip": "29th June",
            "rating": "BBB- by ICRA & BBB+ by CARE",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs  (Limited Qtm)",
            "yield/price": "10.00%",
            "isin": "INE528G08287"
        },
        {
            "category": "Private BONDS",
            "coupon": "10.50%",
            "security": "Indusind Bank Perp",
            "maturity": "28-Mar-24",
            "ip": "28th Mar",
            "rating": "AA by IND ratings & CRISIL",
            "fv": "10 Lac",
            "quantum": "10.00 Lacs Only",
            "yield/price": "8.50%",
            "isin": "INE095A08082"
        },
        {
            "category": "Private BONDS",
            "coupon": "10.8%",
            "security": "MAS Financial Services Ltd. 2027 (Sub-Debt)",
            "maturity": "20-May-27",
            "ip": "20th of Every Month",
            "rating": "A+ by CARE",
            "fv": "1 cr",
            "quantum": "Multiples of 1 cr",
            "yield/price": "11.6%",
            "isin": "INE348L08041"
        },
        {
            "category": "Private BONDS",
            "coupon": "9.20%",
            "security": "Navi Finserv Ltd 2023 (Secured)",
            "maturity": "08-Dec-23",
            "ip": "08th of Every Month",
            "rating": "A (Stable) by IND rating",
            "fv": "1000",
            "quantum": "Multiples of 5 Lacs",
            "yield/price": "10.0%",
            "isin": "INE342T07189"
        },
        {
            "category": "Private BONDS",
            "coupon": "9.50%",
            "security": "Navi Finserv Ltd 2023 (Secured)",
            "maturity": "08-Dec-23",
            "ip": "08th Jun",
            "rating": "A (Stable) by IND rating",
            "fv": "1000",
            "quantum": "Multiples of 5 Lacs",
            "yield/price": "10.0%",
            "isin": "INE342T07197"
        },
        {
            "category": "Private BONDS",
            "coupon": "6.8%",
            "security": "Piramal Capital & Hsg Finance Ltd 2031 (Secured) (Present fv : Rs 975)**",
            "maturity": "28-Mar-2022 (Partial redemption of 2.5% every coupon payment till 28-Sep-2026 and redemption of 7.5% thereafter till 26-Sep-2031)",
            "ip": "28th Sep/28th Mar",
            "rating": "AA by ICRA & CARE",
            "fv": "975",
            "quantum": "Multiples of 9.75 Lacs  (Limited Qtm)",
            "yield/price": "11.70%",
            "isin": "INE516Y07444"
        },
        {
            "category": "Private BONDS",
            "coupon": "9.40%",
            "security": "Hinduja Leyland Finance Ltd 2024 (Sub-debt)",
            "maturity": "28-Aug-24",
            "ip": "28th Aug",
            "rating": "AA- by CARE",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "9.20%",
            "isin": "INE146O08100"
        },
        {
            "category": "Private BONDS",
            "coupon": "10.3%",
            "security": "Shriram Transport Finance Company Ltd. 2024 (Unsecured- Subordinate Tier 2)",
            "maturity": "26-Apr-24",
            "ip": "28th of Every Month",
            "rating": "AA+ by CRISIL & IND ratings",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs  (Limited Qtm)",
            "yield/price": "8.9%",
            "isin": "INE721A08DC8"
        },
        {
            "category": "Private BONDS",
            "coupon": "10.3%",
            "security": "Shriram Transport Finance Company Ltd. 2024 (Unsecured- Subordinate Tier 2)",
            "maturity": "27-Dec-24",
            "ip": "28th of Every Month",
            "rating": "AA+ by CRISIL & IND ratings",
            "fv": "10 Lac",
            "quantum": "10.00 Lacs Only",
            "yield/price": "8.90%",
            "isin": "INE721A08DE4"
        },
        {
            "category": "Private BONDS",
            "coupon": "8.6%",
            "security": "Shriram Housing Finance Ltd. 2025 (Secured) (coupon Fixed as 3 month T-Bill + Fixed Spread of 375 basis)**",
            "maturity": "04-Mar-25",
            "ip": "04th Mar/04th Jun/04th Sep/04th Dec",
            "rating": "AA by IND ratings",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "100.50 (Approx.8.74%)",
            "isin": "INE432R07299"
        },
        {
            "category": "Private BONDS",
            "coupon": "8.0%",
            "security": "Tata Capital Financial Services Ltd 2032 (Secured)",
            "maturity": "12-Aug-32",
            "ip": "12th Aug",
            "rating": "AAA by CRISIL & ICRA",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.9%",
            "isin": "INE306N07MZ5"
        },
        {
            "category": "Private BONDS",
            "coupon": "8.6%",
            "security": "HDFC Ltd 2029 (Secured)",
            "maturity": "27-Mar-29",
            "ip": "27th Mar",
            "rating": "AAA by CRISIL & ICRA",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.7%",
            "isin": "INE001A07RT1"
        },
        {
            "category": "Private BONDS",
            "coupon": "7.0%",
            "security": "HDFC Ltd 2031 (Secured)",
            "maturity": "01-Dec-31",
            "ip": "01st Dec",
            "rating": "AAA by CRISIL & ICRA",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.70%",
            "isin": "INE001A07TG4"
        },
        {
            "category": "Private BONDS",
            "coupon": "8.00%",
            "security": "HDFC Ltd 2032 (Secured)",
            "maturity": "27-Jul-32",
            "ip": "27th Jul",
            "rating": "AAA by CRISIL & ICRA",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.8%",
            "isin": "INE001A07TO8"
        },
        {
            "category": "Private BONDS",
            "coupon": "7.9%",
            "security": "LIC Hsg Finance Ltd 2032 (Secured)",
            "maturity": "18-Aug-32",
            "ip": "18th Aug",
            "rating": "AAA by CRISIL & CARE",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "7.8%",
            "isin": "INE115A07PY3"
        },
        {
            "category": "Private BONDS",
            "coupon": "5.50%",
            "security": "Britannia Industries Limited 2024 (Unsecured) (fv Rs.29)",
            "maturity": "03-Jun-24",
            "ip": "03rd Jun",
            "rating": "AAA by CRISIL & ICRA",
            "fv": "29",
            "quantum": "Multiples of 3 Lacs",
            "yield/price": "6.4%",
            "isin": "INE216A08027"
        },
        {
            "category": "Private BONDS",
            "coupon": "7.90%",
            "security": "Cholamandalam Investment & Finance Company Limited 2031 (Sub-Debt)",
            "maturity": "06-Oct-31",
            "ip": "04th Oct",
            "rating": "AA+ by IND ratings & ICRA",
            "fv": "1 Cr",
            "quantum": "Multiples of 1 Cr",
            "yield/price": "8.3%",
            "isin": "INE121A08OR6"
        },
        {
            "category": "Private BONDS",
            "coupon": "9.30%",
            "security": "Indiabulls Housing Finance Ltd 2026 (Sub-debt)",
            "maturity": "29-Jun-26",
            "ip": "29th June",
            "rating": "AA+ by BWR & AA by CARE",
            "fv": "1 Lac",
            "quantum": "Multiple of 10 Lacs",
            "yield/price": "10.00%",
            "isin": "INE148I08215"
        },
        {
            "category": "Private BONDS",
            "coupon": "7.8%",
            "security": "Star Union Dai-Ichi Life Insurance Company Ltd 2031 (Sub-debt)",
            "maturity": "24-Nov-2026",
            "ip": "24th Nov",
            "rating": "AA by ICRA & CARE",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "8.3%",
            "isin": "INE503V08016"
        },
        {
            "category": "Private BONDS",
            "coupon": "10.00%",
            "security": "Aptus Value Housing Finance India Ltd 2025 (Secured)",
            "maturity": "20-Aug-2023",
            "ip": "1st of every Month",
            "rating": "AA- by ICRA",
            "fv": "1 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "8.00%",
            "isin": "INE852O07097"
        },
        {
            "category": "Private BONDS",
            "coupon": "11.6%",
            "security": "Clix Capital Services Pvt Ltd 2023 (Unsecured)",
            "maturity": "25-May-23",
            "ip": "31st of every Month",
            "rating": "A by CARE",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "11.50%",
            "isin": "INE157D08019"
        },
        {
            "category": "Private BONDS",
            "coupon": "9.00%",
            "security": "SK Finance Ltd 2025 (Secured,Unlisted)",
            "maturity": "11-May-2023 : 33.3300%   11-May-2024 :33.3300% 11-May-2025 : 33.3400%",
            "ip": "11th May",
            "rating": "A+ by CRISIL",
            "fv": "10000",
            "quantum": "Multiples of 5 Lacs",
            "yield/price": "100",
            "isin": "INE124N07580"
        },
        {
            "category": "Private BONDS",
            "coupon": "11.8%",
            "security": "Svatantra MicroFin Pvt Ltd 2027 (Sub-Debt, Unlisted)",
            "maturity": "27-Jul-27",
            "ip": "27th Jul/27th Jan",
            "rating": "A+ by CRISIL",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "10.80%",
            "isin": "INE00MX08078"
        },
        {
            "category": "Private BONDS",
            "coupon": "11.8%",
            "security": "Svatantra MicroFin Pvt Ltd 2027 (Sub-Debt, Unlisted)",
            "maturity": "27-Jul-27",
            "ip": "27th Jul/27th Jan",
            "rating": "A+ by CRISIL",
            "fv": "10 Lac",
            "quantum": "Multiples of 1 cr",
            "yield/price": "10.90%",
            "isin": "INE00MX08078"
        },
        {
            "category": "Private BONDS",
            "coupon": "8.40%",
            "security": "Avanse Financial Services Ltd 2023 (Secured)",
            "maturity": "27-Jul-27",
            "ip": "30th Jul",
            "rating": "A+ by CARE",
            "fv": "10 Lac",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "8.00%",
            "isin": "INE087P07170"
        },
        {
            "category": "Private BONDS",
            "coupon": "10.50%",
            "security": "VISTAAR FINANCIAL SERV PVT LTD (Secured)",
            "maturity": "27-Jul-27",
            "ip": "30th of every Month",
            "rating": "A/Stable by ICRA ratings",
            "fv": "10 Lacs",
            "quantum": "Multiples of 10 Lacs",
            "yield/price": "9.3%",
            "isin": "INE016P07146"
        },
        {
            "category": "Private BONDS",
            "coupon": "11.00%",
            "security": "Kogta Financial (India) Ltd 2023 (Secured) (fv 43,322)",
            "maturity": "27-Jul-27",
            "ip": "10th of every Month",
            "rating": "A by CARE",
            "fv": "43322",
            "quantum": "Multiples of 4.3322 Lacs",
            "yield/price": "9.50%",
            "isin": "INE192U07186"
        }
    ]
}