export { default as Splashscreen } from './Splashscreen';
export { default as Onboardingscreen } from './Authscreens/Onboardingscreen';
export { default as Loginscreen } from './Authscreens/Loginscreen';
export { default as Signupscreen } from './Authscreens/Signupscreen';
export { default as Homescreen } from './Appscreens/Homescreen';
export { default as Searchscreen } from './Appscreens/Searchscreen';
export { default as Portfolioscreen } from './Appscreens/Portfolioscreen';
export { default as Profilescreen } from './Appscreens/Profilescreen';
export { default as Securityscreen } from './Options/Securityscreen';
export { default as Mobileverification } from './Options/Mobileverification';
export { default as Emailverification } from './Options/Emailverification';
export { default as AdvanceKYC } from './Options/AdvanceKYC';
export { default as Addmoney } from './Options/Addmoney';
export { default as KYCwaiting } from './Options/KYCwaiting';
export { default as Appfeedback } from './Options/Appfeedback';
export { default as Transaction } from './Options/Transaction';
export { default as Aboutus } from './Options/Aboutus';
export { default as Contactus } from './Options/Contactus';
export { default as Orders } from './Options/Orders';
export { default as Profile } from './Options/Profile';
export { default as InvitenEarn } from './Options/InvitenEarn';
export { default as Profilemain } from './Options/Profilemain';
export { default as Bankdetails } from './Options/Bankdetails';
export { default as Userprofile } from './Options/Userprofile';
export { default as Demataccount } from './Options/Demataccount';
export { default as HelpnSupport } from './Options/HelpnSupport';
export { default as Helpnsupportdetails } from './Options/Helpnsupportdetails';
export { default as HelpnSupportRequest } from './Options/HelpnSupportRequest';
export { default as HelpnSupportchat } from './Options/HelpnSupportchat';
// export { default as Orders } from './Options/Orders';
// export { default as Orders } from './Options/Orders';
// export { default as InvitenEarn } from './Appscreens/InvitenEarn';
// export { default as Homescreen } from './Appscreens/Homescreen';
// export { default as colors } from './colors';